package com.cintap.transport.entity.edifact.orders;
// Generated May 11, 2022 4:17:20 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * EdifactDesadvLineItem generated by hbm2java
 */
@Entity
@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "edifact_orders_line_item", catalog = "cintap_transport")
public class OrdersLineItem implements java.io.Serializable {

	private static final long serialVersionUID = 6802960275302676183L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne
	@JoinColumn(name = "edifact_orders_header_id")
	@JsonIgnoreProperties("lstOrdersLineItem")
	private OrdersHeader ordersHeader;
	
	@Column(name = "item_line_number", length = 50)
	private String itemLineNumber;
	
	@Column(name = "asus_part_number", length = 255)
	private String asusPartNumber;
	
	@Column(name = "additional_part_number", length = 255)
	private String additionalPartNumber;
	
	@Column(name = "supplier_part_description", length = 255)
	private String supplierPartDescription;
	
	@Column(name = "quantity", length = 50)
	private String quantity;
	
	@Column(name = "unit_price", length = 50)
	private String unitPrice;
	
	@Column(name = "free_text_stock_file", length = 255)
	private String freeTextStockFile;

	@Column(name = "free_text_condition_code", length = 255)
	private String freeTextConditionCode;

}
