package com.cintap.transport.entity.edifact.desadv;
// Generated May 11, 2022 4:17:20 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * EdifactDesadvLineItem generated by hbm2java
 */
@Entity
@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "edifact_desadv_line_item", catalog = "cintap_transport")
public class EdifactDesadvLineItem implements java.io.Serializable {

	private static final long serialVersionUID = 6802960275302676183L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne
	@JoinColumn(name = "edifact_desadv_header_id")
	@JsonIgnoreProperties("edifactDesadvLineItems")
	private DespatchAdviceHeader edifactDesadvHeader;
	
	@Column(name = "item_line_number", length = 50)
	private String itemLineNumber;
	
	@Column(name = "vendor_part_number", length = 50)
	private String vendorPartNumber;
	
	@Column(name = "buyer_part_number", length = 50)
	private String buyerPartNumber;
	
	@Column(name = "vendor_part_description", length = 50)
	private String vendorPartDescription;
	
	@Column(name = "supplier_part_description", length = 50)
	private String supplierPartDescription;
	
	@Column(name = "quantity", length = 50)
	private String quantity;
	
	@Column(name = "total_pallet_count", length = 50)
	private String totalPalletCount;
	
	@Column(name = "total_carton_count", length = 50)
	private String totalCartonCount;
	
	@Column(name = "unit_price", length = 50)
	private String unitPrice;
	
	@Column(name = "free_text")
	private String freeText;
	
	@Transient
	private String referenceIdentifier;

}
